server:
  port: 8761
spring:
  application:
    name: naming-server
  management:
    tracing:
      sampling:
        probability: 0.5
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false